# Generated by Django 4.2.3 on 2023-07-22 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("buyer_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("password", models.TextField(blank=True, null=True)),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "identification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("staff_id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                (
                    "type_of_employment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=50, null=True)),
                ("position", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("unit_price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
                ("town", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.SmallIntegerField(choices=[(0, "Active"), (1, "Inactive")]),
                ),
                (
                    "cooperative_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "national_card",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pwd", models.SmallIntegerField(blank=True, null=True)),
                (
                    "form_of_disability",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("total_amount", models.FloatField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tondaar_app_v1.buyer",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tondaar_app_v1.employee",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tondaar_app_v1.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductInventory",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tondaar_app_v1.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tondaar_app_v1.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyerAddress",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                ("address_line1", models.CharField(max_length=100)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=15)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tondaar_app_v1.buyer",
                    ),
                ),
            ],
        ),
    ]
